### ISSUE TITLE
Gradle 2.14 Breaks Plugin "No service of type ProgressLoggerFactory available in ProjectScopeServices"

### ISSUE THREAD

**Issue by mgoovaer** [x2on/gradle-hockeyapp-plugin#85] opened 2016-06-21 20:50 UTC
Gradle 2.13 still works but after updating to 2.14 (in my gradle-wrapper.properties file) I receive the following error when trying to upload a build:
**Execution failed for task ':app:uploadQaDebugToHockeyApp'.**
> No service of type ProgressLoggerFactory available in ProjectScopeServices.

Attached is the full stack trace.
[hockeyapperror.txt](https://github.com/x2on/gradle-hockeyapp-plugin/files/326561/hockeyapperror.txt)

**Comment by tkirshboim** [comment] 2016-07-04 08:41
I found another gradle plugin that had the same issue and fixed it, but I didn't dive into the details to tell if their solution is applicable to this project:
https://github.com/openbakery/gradle-xcodePlugin/issues/275

**Comment by atakankaya** [comment] 2016-07-18 14:20
I don't want to be pushy on this but is there any schedule of the next update of this plugin with this fix? We will plan to configure our build servers to use the previous version of gradle if it will take some more time. But I wanted to double check with you whether it will take more time to receive an update with the fix.

**Comment by schlan** [comment] 2016-07-20 15:54
I'm with @atakankaya, it'd be cool to get this fixed.

**Comment by x2on** [comment] 2016-07-20 16:02
I will make a release soon - sorry for the waiting time

**Comment by x2on** [comment] 2016-07-21 16:11
Fixed in 3.5

**Closed by x2on** 2016-07-21 16:11 UTC

**Comment by palaima** [comment] 2016-07-22 07:39
`Could not find de.felixschulze.gradle:gradle-hockeyapp-plugin:3.5`
when 3.5 version will be published?

**Comment by x2on** [comment] 2016-07-22 07:58
Should be available in 1-2 hours on maven central

**Comment by kenyee** [comment] 2016-07-25 02:48
Thanks for the quick response x2on :-)

**Comment by kenyee** [comment] 2017-03-05 03:04
Is this back with Gradle 3.3 and Android Studio/plugin 2.3?

> * Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mobile:uploadDebugToHockeyApp'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.internal.service.UnknownServiceException: No service of type ProgressLoggerFactory available in ProjectScopeServices.
        at org.gradle.internal.service.DefaultServiceRegistry.getServiceProvider(DefaultServiceRegistry.java:436)
        at org.gradle.internal.service.DefaultServiceRegistry.doGet(DefaultServiceRegistry.java:426)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:410)
        at org.gradle.internal.service.ServiceRegistry$get.call(Unknown Source)
        at de.felixschulze.gradle.HockeyAppUploadTask.uploadAppplicationFileToHockeyApp(HockeyAppUploadTask.groovy:150)
        at de.felixschulze.gradle.HockeyAppUploadTask$uploadAppplicationFileToHockeyApp.callCurrent(Unknown Source)
        at de.felixschulze.gradle.HockeyAppUploadTask.upload(HockeyAppUploadTask.groovy:145)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more
